name: YouTube Auto Upload

on:
  schedule:
    - cron: "0 */5 * * *"   # हर 5 घंटे में run
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run video generation + upload
        run: python main.py
        
