name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.2.0
        with:
        python-version: "3.10"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: List files (debug)
      run: ls -R

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./

    - name: Run main script
      run: python main.py
