name: YouTube Shorts Automation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checks out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Sets up the Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Installs the latest versions of all required libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-genai moviepy google-api-python-client google-auth-oauthlib requests

      # Step 4: Runs your main Python script with secrets
      - name: Run script
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: python main.py
        
