name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"   # Har 5 ghante me chalega

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --prefer-binary -r requirements.txt

      - name: Write secrets to files
        run: |
          echo "$TOKEN_JSON" > token.json
          echo "$CONFIG_JSON" > config.json
          echo "$CLIENT_SECRET_JSON" > client_secret.json
        shell: bash
        env:
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
          CONFIG_JSON: ${{ secrets.CONFIG_JSON }}
          CLIENT_SECRET_JSON: ${{ secrets.CLIENT_SECRET_JSON }}

      - name: Run video generation + upload
        run: |
          echo "✅ Script started..."
          python main.py
          
