name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4 pinned

    - name: Set up Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5 pinned
      with:
        python-version: "3.10"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: List files (debug)
      run: ls -R

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Run main script
      run: python main.py
      working-directory: ${{ github.workspace }}
      
