name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3

    - name: Set up Python
      uses: actions/setup-python@13ae6addf04891f7a5c391fa3efb2f4d5f38e819 # v4
      with:
        python-version: "3.10"

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: List files (debug)
      run: ls -R

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ./

    - name: Run main script
      run: python main.py
      
