Name: YouTube Shorts Automation

on:
  schedule:
    - cron: "0 */5 * * *"   # ⏰ Runs every 5 hours
  workflow_dispatch:         # 🔘 Allows manual runs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # ✅ Install dependencies
      - name: Install dependencies
        # FIX: Corrected the indentation of the 'run' command
        run: pip install --no-cache-dir --upgrade -r requirements.txt
  
      # ✅ Run main.py
      - name: Run script
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
        run: python main.py
        
