name: YouTube Shorts Auto Upload

on:
  workflow_dispatch:   # manually run karne ke liye
  schedule:
    - cron: "0 */5 * * *"   # har 5 ghante me ek baar (UTC time)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@f213d3c485d8a3e811a4c21c6d4e8e85c36e86a0

      - name: Set up Python
        uses: actions/setup-python@82c76e31bb3dc910f68e0081cb32635878777bc
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
        run: python main.py
