name: YouTube Auto Upload

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *"   # har 5 ghante (UTC)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # ⬇️ Checkout without actions/checkout (download archive via API)
      - name: Download source archive (no actions/checkout)
        env:
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Downloading tarball for $REPO @ $SHA"
          curl -L \
            -H "Authorization: Bearer ${TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            -o src.tar.gz \
            https://api.github.com/repos/${REPO}/tarball/${SHA}
          tar -xzf src.tar.gz
          # move extracted folder contents to workspace root
          EXTRACTED_DIR="$(find . -maxdepth 1 -type d -name '-' | head -n 1)"
          shopt -s dotglob
          mv "$EXTRACTED_DIR"/* .
          shopt -u dotglob
          rm -rf "$EXTRACTED_DIR" src.tar.gz
          ls -la

      - name: Python available?
        run: |
          python3 --version
          python3 -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Run one generation+upload
        env:
          YT_CLIENT_ID:     ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          GEMINI_API_KEY:   ${{ secrets.GEMINI_API_KEY }}
          HF_TOKEN:         ${{ secrets.HF_TOKEN }}
          PEXELS_API_KEY:   ${{ secrets.PEXELS_API_KEY }}
        run: |
          python3 main.py
