name: YouTube Shorts Auto Upload
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Manual checkout (no actions/checkout)
        env:
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          git init
          git remote add origin https://github.com/${REPO}.git
          git fetch --depth=1 origin ${SHA}
          git checkout -q FETCH_HEAD

      - name: Use system Python (no setup-python)
        run: |
          python3 --version
          python3 -m pip install --upgrade pip wheel setuptools

      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt

      - name: Run script
        env:
          YT_CLIENT_ID:     ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          GEMINI_API_KEY:   ${{ secrets.GEMINI_API_KEY }}
          HF_TOKEN:         ${{ secrets.HF_TOKEN }}
          PEXELS_API_KEY:   ${{ secrets.PEXELS_API_KEY }}
        run: |
          python3 main.py
